services:
  - type: web
    name: church-website
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
